### ISSUE TITLE
Storyboard files

### ISSUE THREAD

**Issue by acegreen** [LaunchKit/launchkit-ios#16]
Hey, 

I mentioned this in an email but it would be great if we have access to LaunchKits storyboard files. The UI is ideal for a lot of use cases including in-app purchases. This would avoid users duplicating.

**Comment by taylorhughes** [comment]
Storyboards from LK codebase will not be very helpful as they are used like templates that are manipulated through a set of transformations in cryptic python. They are also bound to various classes in our client SDK. I did not include them here because it would be too complicated for any reasonable person to get working.

**Comment by acegreen** [comment]
Fair enough. In an idea world, libraries could build on top of the others work. Another example is LK segues that are surely created by other libraries as well.
